export const healthyBody = {
  head: { status: "ok", injuries: [] },
  torso: { status: "ok", injuries: [] },
  leftArm: { status: "ok", injuries: [] },
  rightArm: { status: "ok", injuries: [] },
  leftLeg: { status: "ok", injuries: [] },
  rightLeg: { status: "ok", injuries: [] },
};

export const initialGameState = {
  mode: "character_select",
  selectedCharacterId: null,
  worldDecay: 10,
  sin: 0,
  personalDecay: 0,
  currentCity: null,
  hero: {
    id: null,
    name: "Герой не выбран",
    race: null,
    portrait: null,
    location: null,
    cityLocation: null,
    locationMapNode: null,
    day: 1,
    hp: 0,
    maxHp: 0,
    fatigue: 0,
    trace: 0,
    actionsMax: 1,
    actionsLeft: 1,
    stats: { strength: 0, agility: 0, defense: 0, perception: 0, charisma: 0, will: 0, intellect: 0 },
    body: structuredClone(healthyBody),
    equipment: { mainHand: null, offHand: null, armor: null, accessory: null },
    inventory: [],
  },
  party: { companions: [] },
  world: { knownNodes: [], visitedNodes: [], revealedByRumor: [], threat: 1 },
  npcPlayers: [],
  reputation: {},
  activeEvent: null,
  activeCombat: null,
  travel: { active: false, fromNodeId: null, toNodeId: null, daysRemaining: 0, eventResolved: false },
  activeMessage: "Выбери героя, с которого начнётся путь по Эйре.",
  lore: { discoveredFragments: [], discoveredCollections: [], unreadFragments: [] },
  journal: [],
};

export function createInitialStateForCharacter(character) {
  return {
    ...initialGameState,
    mode: "world",
    selectedCharacterId: character.id,
    worldDecay: 10,
    sin: 0,
    personalDecay: 0,
    currentCity: null,
    hero: {
      id: character.id,
      name: character.name,
      race: character.race,
      portrait: character.portrait,
      location: character.startLocationId,
      cityLocation: null,
      locationMapNode: null,
      day: 1,
      hp: character.start.hp,
      maxHp: character.start.maxHp,
      fatigue: character.start.fatigue,
      trace: character.start.trace,
      actionsMax: character.start.actionsMax,
      actionsLeft: character.start.actionsLeft,
      stats: structuredClone(character.stats),
      body: structuredClone(healthyBody),
      equipment: structuredClone(character.start.equipment),
      inventory: [...character.start.inventory],
    },
    party: { companions: [] },
    world: {
      knownNodes: [character.startLocationId],
      visitedNodes: [character.startLocationId],
      revealedByRumor: [],
      threat: 1,
    },
    npcPlayers: [],
    reputation: {},
    activeEvent: null,
    activeCombat: null,
    travel: {
      active: false,
      fromNodeId: null,
      toNodeId: null,
      daysRemaining: 0,
      eventResolved: false,
    },
    activeMessage: `Путь начинается: ${character.name}.`,
    lore: {
      discoveredFragments: [],
      discoveredCollections: [],
      unreadFragments: [],
    },
    journal: [`День 1. Путь начинается: ${character.name}.`],
  };
}

export function cloneState(gameState) {
  return structuredClone(gameState);
}
